# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f76893fedeafe85e9cd1e68618602bc4"
name = "ShineW Pride Backend"
application_url = "https://shinewpridebackend-production.up.railway.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,write_customers,write_app_proxy"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

[auth]
redirect_urls = [
  "https://shinewpridebackend-production.up.railway.app/auth/callback",
  "https://shinewpridebackend-production.up.railway.app/auth/shopify/callback",
  "https://shinewpridebackend-production.up.railway.app/api/auth/callback"
]

[app_proxy]
url = "https://shinewpridebackend-production.up.railway.app/proxy"
prefix = "apps"
subpath = "shinewpride"

[build]
automatically_update_urls_on_dev = true
